spring:
  datasource:
    username: root
    password: Ldy9290804
    url: jdbc:mysql://localhost:3306/taskdemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver